-- Names from fake players addon https://github.com/C0nw0nk/Garrys-Mod-Fake-Players

D3bot.Names = {
	"Garry :D",
	"Rubat",
	"Rainbow Dash",
	"Jaffa Cake",
	"Sweetex",
	"Meta",
	"Fluttershy",
	"Trigger",
	"T-REX",
	"Meow :3",
	"Twilight Sparkle",
	"~Katt~ <3",
	"The G-Unit",
	"Derp",
	"Rarity",
	"Shade",
	"Fee",
	"Pinky Pie",
	"Foo Foo",
	"d(^_^)b",
	"Kitty",
	"Buttercup",
	"Fluffy",
	"Derpy Hooves",
	"Foxxi ♥",
	"Defcon",
	"Xira",
	"Pound Cake",
	"Xenia",
	"Steam.exe",
	"Scootalo",
	"Prodigy",
	"MKA0208",
	"Flump",
	"Mrs. Cup Cake",
	"Boom Headshot!",
	"Cookie",
	"Flesh Pound",
	"Snips",
	"C4k3",
	"Rabit",
	"GirlDeaa",
	"Lemon",
	"Apple Bloom",
	"Obama",
	"Volition",
	"Sweetie Belle",
	"BellaTrix",
	"Atomic Boom!",
	"Nuclear Reactor Party!",
	"Donald Trump",
	"DION",
	"Swexy",
	"Spyro",
	"Super Man",
	"Khaleesi",
	"DYSON",
	"Pixies",
	"Rayman",
	"Andrax",
	"SpY",
	"Los Lobos",
	"Foxy",
	"Big Macintosh",
	"Tiny Tim",
	"BASSHUNTER",
	"Scooter",
	"Princess Luna",
	"D00p",
	"AppleJack",
	"C4sp3r",
	"Moi Loca",
	"Gaben",
	"Mina | <3",
	"Cr33p3r",
	"1+3+3=7",
	"Gabe Newell",
	"1+1=11",
	"Mojo Jojo",
	"┌∩┐(◣_◢)┌∩┐",
	"Cerberus",
	"Pr0",
	"The Salt Bar",
	"Bubbles",
	"Zeus",
	"Snapshot",
	"Floofy",
	"dudette",
	"Coach",
	"TANK",
	"ρanda♥",
	"K9 Lady",
	"Woody",
	"<3 FEMALE META | :3",
	"Salami Lid",
	"Mr.Roflman 65",
	"Medical Dude",
	"Shit Medics",
	"Redeem me plz",
	"Skycade Hater",
	"Solocade Breaker",
	"Leroy Jenkins",
	"Skill Issue",
	"Built Different",
	"VOTE MAKO",
	"shitcader",
	"Free RPG",
	"hey beter",
	"snooth",
	"FLARE MAG",
	"I was a lootbag",
	"Prop Kill Incoming",
	"Headcrab Gaming",
	"pepe",
	"A Cader",
	"B Cader",
	"C cader",
	"Nerf Zombies",
	"Nerf Humans",
	"Navmesh Tester",
	"League Player",
	"Baguette",
	"Grievous Wounds Enjoyer",
	"NEST PLS",
	"UNSTUCK ME",
	"HTEAM COOKED",
	"ZTEAM COOKED",
	"Wave 1 Wipe",
	"ArthurofHex",
	"BUY ARMOR",
	"Batman",
	"Add Bots",
	"REPAIR"
}